# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_countrynames'),
    ]

    operations = [
        migrations.CreateModel(
            name='countryLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layername', models.CharField(max_length=50)),
                ('countrylist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='countryNames',
        ),
    ]
