# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20170320_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='countrylists',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrylists',
            name='relatedmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.UserMaps'),
        ),
    ]
