# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_auto_20170403_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrylists',
            name='info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='countrylists',
            name='layername',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='countrylists',
            name='year',
            field=models.IntegerField(),
        ),
    ]
