# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_auto_20170404_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrylists',
            name='layercolour',
            field=models.CharField(default='blue', max_length=50),
            preserve_default=False,
        ),
    ]
